apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-cr
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
    project: default
    source:
        repoURL: https://github.com/venk404/venk404-Helm-Assignments-k8s.git
        targetRevision: main
        path: helm/External-secrets/external-secrets-cr
        helm:
          parameters:
            - name: secret.token
              value: <token>
    destination:
      server: https://kubernetes.default.svc
      namespace: external-secrets
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
        - PrunePropagationPolicy=Foreground
