name: Update Helm Chart CD
on:
  repository_dispatch:
    types: [update-image]
jobs:
  update-helm-chart:
    runs-on: self-hosted
    
    steps:
    - name: Debug - Print JSON payload
      run: |
        echo "=== WHAT THE WORKFLOW IS GETTING ==="
        echo '${{ toJson(github.event.client_payload) }}'
        echo "=================================="
        
    - name: Checkout Helm charts repository
      uses: actions/checkout@v4
      with:
        repository: venk404/venk404-Helm-Assignments-k8s
        token: ${{ secrets.PAT_TOKEN }}
        path: helm-repo

    - name: install yq
      run: |
        # Install yq if not already available
        if ! command -v yq &> /dev/null; then
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod a+x /usr/local/bin/yq
        fi  
        
    - name: Update Helm chart with latest image tags
      run: |
        VERSION="${{ github.event.client_payload.restapi_version }}"
        
        if [ ! -z "$VERSION" ]; then
          echo "Updating image versions to: $VERSION"
          
          # Update both tags in one command
          yq e "
            .application.image.tag = \"$VERSION\" |
            .application.migration.image.tag = \"$VERSION\"
          " -i helm-repo/helm/Restapi/values.yaml
          
          echo "Updated values.yaml:"
          cat helm-repo/helm/Restapi/values.yaml
        fi
        
        
        echo "Updated images: $UPDATED_IMAGES"
        echo "=================================="
        echo "Updated values.yaml after changes:"
        cat helm-repo/helm/Restapi/values.yaml
        
    - name: Commit and push changes
      run: |
        cd helm-repo
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        
        # Check if there are any changes
        if git diff --quiet HEAD -- helm/Restapi/values.yaml; then
          echo "No changes detected in values.yaml"
          exit 0
        fi
        
        git add helm/Restapi/values.yaml
        
        # Simplified commit message using the same version for both
        COMMIT_MSG="Update Helm chart: studentapi and migration to version ${{ github.event.client_payload.restapi_version }}"
        
        echo "Committing with message: $COMMIT_MSG"
        git commit -m "$COMMIT_MSG"
        git push